preload = /home/pulsar/Wallpapers/Active/a_tree_in_a_body_of_water_with_mountains_in_the_background.jpg
wallpaper = ,/home/pulsar/Wallpapers/Active/a_tree_in_a_body_of_water_with_mountains_in_the_background.jpg
splash = false
ipc = true
